### ISSUE TITLE
last_params

### ISSUE THREAD

**Issue by wdlv** [SdeBlank/NanoFG#12]
Hi Sam,

We have got some errors when running your software. The error is:
/LAST/src/lastal: can't open file: /LAST/last_params

Could you tell us what is last_params?

Thanks,

Hongwei

**Comment by SdeBlank** [comment]
Hi,

The last_params file contains trained scoring parameters for a particular aligment. It can be created by:
`lastdb [referencedb] [reference.fa]`
`last-train -Q1 [referencedb] [reads_sample.fastq] > last_params`

I uploaded the last_params file we have used for mapping nanopore data in the files directory:
https://github.com/SdeBlank/NanoFG/tree/master/files

For a full explanation on how to run LAST you could take a look at:
https://github.com/mroosmalen/nanosv#running-last

Hopefully this helps

Cheers,
Sam

**Comment by wdlv** [comment]
Thanks for your reply!
