### ISSUE TITLE
Multiple hardcoded paths in your code

### ISSUE THREAD

**Issue by nvpatkar** [SdeBlank/NanoFG#13]

**Comment by SdeBlank** [comment]
Hi,

There were indeed a few hardcoded default values left in the pipeline (master branch). However, when running NanoFG, the paths.ini file should override these values. So updating the values in this paths.ini file should work. I also updated the default values for the scripts in the pipeline folder to also take the default paths from this paths.ini file. Hopefully this works!

Cheers,
Sam
