### ISSUE TITLE
How to input the primer information?

### ISSUE THREAD

**Issue by wbaopaul** [SdeBlank/NanoFG#14]
Hi,
Thanks for providing this tool. I have some difficulty in running it. I have long-read seq data trying to detect fusion. How do I give the primer information? 
Do you have an example? Thanks a lot!

**Comment by SdeBlank** [comment]
Hey,

If you mean the primers file (.primers), it is one of the outputs of NanoFG. It contains possible primers for validation of the detected fusions and is not used as an input for NanoFG. 

What you can provide to NanoFG is a '-s | --selection' parameter to only detect fusions in certain regions, which can speed the detection process up. You can provide a gene name (e.g. TP53), Ensembl identifier (e.g.  ENSG00000141510) or a region (e.g. 17:7565097-7590856).

Is this what you needed?

**Comment by wbaopaul** [comment]
Thanks for the kind response. Now I know I don't have to provide primer infromation in path.ini. I jus got confused about some parameters in the path.ini. I have bam files and interested in detecting fusion related to KMT2A genes.  Which parameters I have to adjust in the path.ini? I have changed some parameters
```
PATH_SV_CALLER=/mnt/isilon/tan_lab/yuw1/R_work_dir/MLLr/NanoFG/nanosv/nanosv/NanoSV.py
PATH_SAMTOOLS=/mnt/isilon/tan_lab/yuw1/local_tools/bin/samtools-1.9/samtools
PATH_LAST_DIR=/mnt/isilon/tan_lab/yuw1/R_work_dir/MLLr/NanoFG/last-1111
PATH_WTDBG2_DIR=/mnt/isilon/tan_lab/yuw1/R_work_dir/MLLr/NanoFG/wtdbg2
PATH_HOMO_SAPIENS_REFFASTA=/mnt/isilon/tan_lab/yuw1/R_work_dir/MLLr/GRCh38/genome.fa
PATH_HOMO_SAPIENS_REFGENOME=/mnt/isilon/tan_lab/chenc6/Tools/SingleCellAnnotation/GRCh38/genes/genes.gtf
PATH_HOMO_SAPIENS_REFDICT=/hpc/cog_bioinf/GENOMES/Homo_sapiens.GRCh37.GATK.illumina/Homo_sapiens.GRCh37.GATK.illumina.dict
PATH_PRIMER_DESIGN_DIR=/hpc/cog_bioinf/cuppen/personal_data/jvalleinclan/tools_kloosterman/primer3/
PATH_MINIMAP2=/mnt/isilon/tan_lab/yuw1/R_work_dir/MLLr/NanoFG/minimap2/minimap2
```
Not sure about PATH_HOMO_SAPIENS_REFGENOME, is this a gtf file? Also not sure about PATH_HOMO_SAPIENS_REFDICT. Can you tell how can I specify these files (or how I can get it)? I guess it's not needed if the input file is a bam file. 

Then, I run my job like this:
```
source venv/bin/activate
bash NanoFG.sh -b my_minimap2.sorted.bam -n MLLr879440_sele -s KMT2A -o MLLr879440_sele
```

Then I got errors like:
```
Tue Oct  6 22:06:01 EDT 2020     Running on m-4-05
### bam (-b) already provided. Skipping minimap2 mapping
Tue Oct  6 22:06:01 EDT 2020     Selecting regions to check for fusion genes...
Tue Oct  6 22:16:42 EDT 2020     SV calling...
Tue Oct  6 22:16:43 2020 Busy with parsing bam file...
Tue Oct  6 22:16:53 2020 Busy with parsing read segments...
Tue Oct  6 22:16:53 2020 Busy with parsing breakpoints...
Tue Oct  6 22:16:53 2020 Busy with reference reads...
Tue Oct  6 22:16:53 2020 Busy with printing to vcf...
Tue Oct  6 22:16:53 EDT 2020     Removing insertions and all variants without a PASS filter...
Tue Oct  6 22:16:53 EDT 2020     Extracting reads that support candidate fusion genes...
Start: 2020-10-06 22:16:57.083752
End: 2020-10-06 22:17:01.459368
Tue Oct  6 22:17:01 EDT 2020     Consensus calling not activated. Use '-cc' to turn consensus calling on
Tue Oct  6 22:17:01 EDT 2020     Mapping candidate fusion genes...
/mnt/isilon/tan_lab/yuw1/R_work_dir/MLLr/NanoFG/last-1111/src/lastal: can't open file: /mnt/isilon/tan_lab/chenc6/Tools/SingleCellAnnotation/GRCh38/genes/genes.gtf.prj
maf-convert: error: [Errno 2] No such file or directory: '/hpc/cog_bioinf/GENOMES/Homo_sapiens.GRCh37.GATK.illumina/Homo_sapiens.GRCh37.GATK.illumina.dict'
Tue Oct  6 22:17:02 EDT 2020     Merging bams...
Tue Oct  6 22:17:02 EDT 2020     Calling SVs...
Tue Oct  6 22:17:02 2020 Busy with parsing bam file...
Traceback (most recent call last):
  File "/mnt/isilon/tan_lab/yuw1/R_work_dir/MLLr/NanoFG/nanosv/nanosv/NanoSV.py", line 83, in <module>
    main()
  File "/mnt/isilon/tan_lab/yuw1/R_work_dir/MLLr/NanoFG/nanosv/nanosv/NanoSV.py", line 71, in main
    utils.parse_bam.parse_bam()
  File "/mnt/isilon/tan_lab/yuw1/R_work_dir/MLLr/NanoFG/nanosv/nanosv/utils/parse_bam.py", line 30, in parse_bam
    bam = pysam.AlignmentFile(NanoSV.opts_bam, 'rb')
  File "pysam/libcalignmentfile.pyx", line 736, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 985, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file has no sequences defined (mode='rb') - is it SAM/BAM format? Consider opening with check_sq=False
Tue Oct  6 22:17:02 EDT 2020     Removing insertions and all variants without a PASS filter...
Tue Oct  6 22:17:02 EDT 2020     Linking and combining SVs for complex fusion detection
Traceback (most recent call last):
  File "/mnt/isilon/tan_lab/yuw1/R_work_dir/MLLr/NanoFG/scripts/CombineSVs.py", line 15, in <module>
    vcf_reader=pyvcf.Reader(vcf)
  File "/mnt/isilon/tan_lab/yuw1/R_work_dir/MLLr/NanoFG/venv/lib/python3.6/site-packages/vcf/parser.py", line 300, in __init__
    self._parse_metainfo()
  File "/mnt/isilon/tan_lab/yuw1/R_work_dir/MLLr/NanoFG/venv/lib/python3.6/site-packages/vcf/parser.py", line 317, in _parse_metainfo
    line = next(self.reader)
StopIteration
Tue Oct  6 22:17:02 EDT 2020     Checking fusion candidates...
  File "/mnt/isilon/tan_lab/yuw1/R_work_dir/MLLr/NanoFG/scripts/FusionCheck.py", line 51
    supporting_reads[original_record.ID]=(len(set(original_record.INFO["ALT_READ_IDS"])), len(set(original_record.INFO["REF_READ_IDS_1"]+original_record.INFO["REF_READ_IDS_2"])), original_record.FILTER)
                   ^
SyntaxError: invalid syntax
!!! FUSION CHECK NOT CORRECTLY COMPLETED... exiting

```

Could you help me out? Thank you so much!

Wenbao

**Comment by SdeBlank** [comment]
The PATH_HOMO_SAPIENS_REFGENOME seems to be fine and correctly generated. 

For the error that kills the pipeline I seem to have found the error. There was a try statement I added but forgot to add an 'except: pass' which resulted in the syntax error. I made a small adjustment on the master branch to fix this and you can pull the small change and I think it should work again.

Small other thing. I see you still have the default PATH_PRIMER_DESIGN_DIR. The pipeline will work fine without it and will just solely report the breakpoint sequences, but if you want to have primers for the detected breakpoints automatically designed you can provide a path to primer3.

Let me know if it works now and if you have any other questions!

**Comment by wbaopaul** [comment]
Thanks for the quick reply. I check it out, but with following new error:
```
Thu Oct  8 12:39:50 EDT 2020     Running on c-0-01
rm: cannot remove ‘MLLr879440_sele/candidate_fusions/*’: No such file or directory
rm: cannot remove ‘MLLr879440_sele/primers/*’: No such file or directory
### bam (-b) already provided. Skipping minimap2 mapping
Thu Oct  8 12:39:50 EDT 2020     Selecting regions to check for fusion genes...
Traceback (most recent call last):
  File "/mnt/isilon/tan_lab/yuw1/R_work_dir/MLLr/NanoFG/scripts/RegionSelection.py", line 43, in <module>
    ensembl_request=EnsemblRestClient.perform_rest_action(server, endpoint, headers, params)
  File "/mnt/isilon/tan_lab/yuw1/R_work_dir/MLLr/NanoFG/scripts/EnsemblRestClient.py", line 47, in perform_rest_action
    data = json.loads(response)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
!!! REGION SELECTION NOT CORRECTLY COMPLETED... exiting

```

Thanks for help,
Wenbao

**Comment by SdeBlank** [comment]
I pushed another fix as it seems the Ensembl client does not return a json anymore without an additional header. Can you check if it works now?

**Comment by wbaopaul** [comment]
Thanks, here is the new error:
```
### bam (-b) already provided. Skipping minimap2 mapping
Thu Oct  8 15:25:24 EDT 2020     Selecting regions to check for fusion genes...
Traceback (most recent call last):
  File "/mnt/isilon/tan_lab/yuw1/R_work_dir/MLLr/NanoFG/scripts/RegionSelection.py", line 5, in <module>
    from EnsemblRestClient import EnsemblRestClient
  File "/mnt/isilon/tan_lab/yuw1/R_work_dir/MLLr/NanoFG/scripts/EnsemblRestClient.py", line 47
    self.req_count += 1
       ^
IndentationError: expected an indented block
!!! REGION SELECTION NOT CORRECTLY COMPLETED... exiting
```

**Comment by SdeBlank** [comment]
Oops used the wrong variable, should be fixed in the master branch now.

**Comment by wbaopaul** [comment]
Thanks. The above problem solved. Then I have other issues:
1) if I use -s gene_name, it seems work on hg19 version. Actually I am using hg38. 
2) then I used -s region model (-s 11:118480492-118500832), then I got following message:
```
Thu Oct  8 21:58:16 EDT 2020     Running on c-1-03
### bam (-b) already provided. Skipping minimap2 mapping
Thu Oct  8 21:58:16 EDT 2020     Selecting regions to check for fusion genes...
NanoFG.sh: line 438: 14795 Broken pipe            $SAMTOOLS view -@ $THREADS $BAM
     14796 Killed                  | grep -f reads.tmp >> $REGION_SELECTION_SAM_OUTPUT
Thu Oct  8 22:00:53 EDT 2020     SV calling...
Thu Oct  8 22:01:00 2020 Busy with parsing bam file...
Thu Oct  8 22:01:11 2020 Busy with parsing read segments...
Thu Oct  8 22:01:11 2020 Busy with parsing breakpoints...
Thu Oct  8 22:01:11 2020 Busy with reference reads...
Thu Oct  8 22:01:11 2020 Busy with printing to vcf...
Thu Oct  8 22:01:13 EDT 2020     Removing insertions and all variants without a PASS filter...
Thu Oct  8 22:01:13 EDT 2020     Extracting reads that support candidate fusion genes...
Start: 2020-10-08 22:01:19.089047
End: 2020-10-08 22:01:25.340269
Thu Oct  8 22:01:25 EDT 2020     Consensus calling not activated. Use '-cc' to turn consensus calling on
Thu Oct  8 22:01:25 EDT 2020     Mapping candidate fusion genes...
/mnt/isilon/tan_lab/yuw1/R_work_dir/MLLr/NanoFG/last-1111/src/lastal: option -Q is inconsistent with the matrix file
Thu Oct  8 22:01:25 EDT 2020     Merging bams...
Thu Oct  8 22:01:25 EDT 2020     Calling SVs...
Thu Oct  8 22:01:26 2020 Busy with parsing bam file...
Thu Oct  8 22:01:36 2020 Busy with parsing read segments...
Thu Oct  8 22:01:36 2020 Busy with parsing breakpoints...
Thu Oct  8 22:01:36 2020 Busy with reference reads...
Thu Oct  8 22:01:36 2020 Busy with printing to vcf...
Thu Oct  8 22:01:36 EDT 2020     Removing insertions and all variants without a PASS filter...
Thu Oct  8 22:01:36 EDT 2020     Linking and combining SVs for complex fusion detection
Thu Oct  8 22:01:36 EDT 2020     Checking fusion candidates...
Start: 2020-10-08 22:01:39.631912
End: 2020-10-08 22:01:39.652384
Thu Oct  8 22:01:39 EDT 2020     Designing primers around fusion breakpoints...
Path to primer3 does not exist. Giving only breakpoint sequences
cat: MLLr879583_region/primers/*.fasta: No such file or directory
rm: cannot remove ‘MLLr879583_region/primers/tmp’: Is a directory
rmdir: failed to remove ‘MLLr879583_region/primers’: Directory not empty
Thu Oct  8 22:01:40 EDT 2020     Done
```

I got no fusions. I am thinking following messages about 
**NanoFG.sh: line 438: 14795 Broken pipe            $SAMTOOLS view -@ $THREADS $BAM
     14796 Killed                  | grep -f reads.tmp >> $REGION_SELECTION_SAM_OUTPUT**. 
and
**option -Q is inconsistent with the matrix file** may be suspicious.

Can you help my about this?

Thanks,
Wenbao

**Comment by SdeBlank** [comment]
1. Indeed NanoFG only uses the hg19 version. For other versions, indeed use the coordinates (-s 11:118480492-118500832).

2. Can you check what's inside your $BAM and reads.tmp? Perhaps one of them is empty or has a wrong structure. Also try to run the samtools view outside of NanoFG and see if it gives a similar error

`$SAMTOOLS view -@ 1 $BAM`
and
`$SAMTOOLS view -@ 1 $BAM | grep -f reads.tmp`

I don't see any syntax error in NanoFG.sh but if separately it doesn't crash I might need to check better

**Comment by wbaopaul** [comment]
I found neigher of them are empty. I found it's about 130G memory was used during the running (thus killed by lack of memory I guess). Is this typical memory used for NanoFG? Can you think about something to reduce the memory usage.

Thank you so much,

**Comment by SdeBlank** [comment]
The memory usage of NanoFG can sometimes get rather high because of the tools it uses, depending on the size of input files. The tool was originally made for use on a hpc so I haven't put a lot of importance in cutting memory usage down as this was never a bottleneck, but if there are some quick fixes I can try to introduce them to NanoFG
 
Is the 130Gb memory also used by just running samtools view command separately?

**Comment by SdeBlank** [comment]
The command
`$SAMTOOLS view -@ 1 $BAM | grep -f reads.tmp`
reads in the whole bam and then attempts to grep the reads so I think it uses a lot of memory. 

You can perhaps attempt to select these regions yourself from your full bam and use that as input of NanoFG.  There are some different ways to do this, but I don't know if they use less memory. I don't have any large bamfiles, so I haven't tested any of these solutions but they might be worth a try.

Sambamba has a filter method to select on read names and perhaps it uses less memory.  You can - instead of the command above - try something like this:

```
FILENAME="reads.tmp"
LINES=$(cat $FILENAME)
for LINE in $LINES
do
    sambamba view -F "read_name =~ /$LINE/" $BAM >> $REGION_SELECTION_SAM_OUTPUT
done
```

Another possible solution could be the use of Picard (FilterSamReads) as described here, but I haven't tested it myself:
https://gatk.broadinstitute.org/hc/en-us/articles/360036882611-FilterSamReads-Picard-

Then just replace the orignal command with one of the above and use the generated bam as input in NanoFG:
```
REGION_SELECTION_SAM_OUTPUT=${REGION_SELECTION_BAM_OUTPUT/.bam/.sam}
$SAMTOOLS view -H $BAM > $REGION_SELECTION_SAM_OUTPUT
$SAMTOOLS view -@ $THREADS -L $REGION_SELECTION_BED_OUTPUT $BAM | cut -f 1 | sort -k1n | uniq > reads.tmp
---> $SAMTOOLS view -@ $THREADS $BAM | grep -f reads.tmp >> $REGION_SELECTION_SAM_OUTPUT
$SAMTOOLS view -@ $THREADS -h -S -f bam $REGION_SELECTION_SAM_OUTPUT | $SAMTOOLS sort -o $REGION_SELECTION_BAM_OUTPUT /dev/stdin
$SAMTOOLS index $REGION_SELECTION_BAM_OUTPUT
rm reads.tmp
rm $REGION_SELECTION_SAM_OUTPUT
```

**Comment by wbaopaul** [comment]
Thank you so much for these nice suggestions. I will give it a try. BTW, here is a minor thing but may be helpful: I notice that NanoFG ouputed some files like reads.* on the current directory. But I have multiple files, if I working on them at same time on HPC, it may replace one with another's. Is it possible to output those files to user specified directory. Or maybe there is a way already but I cannot find it. 

Thanks,

**Comment by SdeBlank** [comment]
1. If you specify '-o|--outputdir' you can direct the output ina specific directory. I have found that regions.bed, regions.bam and reads.tmp weren't correctly placed in the outputdir when '-o|--outputdir' was specified. This should be fixed now. If any other files are still incorrectly outputted please let me know so I can fix them.

2. I added reads.tmp to the optionally deleted files. If you specify '-dc|--dont_clean' it will keep the reads.tmp and other files. If you really want to keep only reads.tmp but none of the other you can of course remove this line yourself from the NanoFG.sh script (line 686)

**Comment by wbaopaul** [comment]
Great! Thank you so much for all these helps !
