### ISSUE TITLE
error in FusionCheck.py Request failed for http://grch37.rest.ensembl.org/lookup/id/ENSG00000165609: Status code: 503 Reason: Service Unavailable Request failed for http://grch37.rest.ensembl.org/lookup/id/ENSG00000165630: Status code: 503 Reason: Service Unavailable

### ISSUE THREAD

**Issue by chaimol** [SdeBlank/NanoFG#15]
when I use the ./scripts/FusionCheck.py  for analysis the Fusion gene,there are some error info .just like this
````
Request failed for http://grch37.rest.ensembl.org/lookup/id/ENSG00000165609: Status code: 500 Reason: Internal Server Error
Request failed for http://grch37.rest.ensembl.org/overlap/region/human/10:101708630-101708630?feature=transcript: Status code: 503 Reason: Service Unavailable
```

I know the reason course of the `grch37.rest.ensembl.org` 's server can not be connect. but i can connect the webpage `http://grch37.rest.ensembl.org/lookup/id/ENSG00000165609` in Google Chrome brower. Do you have some idea for handle this problem ?

**Comment by SdeBlank** [comment]
I do not seem to have an issue running NanoFG (on the demo set). 
Perhaps try the demo set as well and see if it does work there.

However, it probably does not either, the EnsemblRestClient.py already seems to fail in connecting to the server.

 There can also be rate-limiting on the ensembl rest server if too many requests are made in a short period of time. Do you have a high amount of fusion genes? The RestClient should however, limit this already, but it might be possible
