### ISSUE TITLE
*.no_ctg.fa

### ISSUE THREAD

**Issue by N-damo** [SdeBlank/NanoFG#16]
dear developer,
I wish you could give me some help,
i used your demo fastq to test the pipeline,
command: bash NanoFG.sh -f NanoFG/demo/demo_fastqdir
error:
![image](https://user-images.githubusercontent.com/43883112/98090177-a709f800-1ebe-11eb-882a-c10b995d43a8.png)

**Comment by SdeBlank** [comment]
That error occurs if there are no fusions to be found, but I need to check while it still creates a *.no_ctg.fa file.

However, I think the error for no detection on the demo set might be the setup of the human reference fasta that is used. 

The human reference fasta input NanoFG can run with is currently limited to fasta files with a setup where the name is the chromosome number:

```
>1 (Instead of Chr1)
NNNNN
>2
NNNNN
># etc.
```

Creation can be done by downloading the reference from:

ftp://ftp.ncbi.nlm.nih.gov/genomes/archive/old_genbank/Eukaryotes/vertebrates_mammals/Homo_sapiens/GRCh37.p13/seqs_for_alignment_pipelines/

and running
```
sed 's/>chr/>/' </PATH/TO/REFERENCE_FASTA> > </PATH/TO/RESULT_FASTA>
```

Additionally using the '-df' setting which does not remove SVs with a filter might make it show up.
```
NanoFG.sh -f NanoFG/demo/demo_fastqdir -df
```

**Comment by N-damo** [comment]
thanks,
more question, can i directly use your provided last_params in NanoFG/files？

**Comment by SdeBlank** [comment]
It is possible to directly use it. However, to get the best scoring parameters for your particular allignment you can train LAST with a subset of reads (>10.000).

```
lastdb [referencedb] [reference.fa]
last-train -Q1 [referencedb] [reads_sample.fastq] > [my-params]
```

In the newest version of NanoFG you can now also do remapping with minimap2 instead of LAST (--without_last). If you don't do consensus calling (-cc) or complex fusion detection (-cf) it will give similar results as the first mapping.

**Comment by WaxRain** [comment]
I downloaded the reference as above described and ran command 
![image](https://user-images.githubusercontent.com/24712670/109121535-562a5200-7782-11eb-9154-8be2f601de06.png)

I got the the same error
![image](https://user-images.githubusercontent.com/24712670/109121776-a99ca000-7782-11eb-905c-abf6b2163f51.png)
and the demo.vcf just has one SV detected.
Why?

**Comment by SdeBlank** [comment]
There were multiple errors that were related to this issue. In the '-wl' there was an error that incorrectly skipped any arguments after the '-wl' argument and some issues with the minimap2 remapping. I have fixed these issues and pushed the correction to the 'master' branch. Let me know if it works now!

**Comment by WaxRain** [comment]
I downloaded the new script and got the fusion result with the command 'bash NanoFG.sh -f demo/demo_fastqdir/ -o tmp -wl
![image](https://user-images.githubusercontent.com/24712670/109244689-19119e80-781a-11eb-92fb-c32a25967730.png)

But I can't get any fusion results with the last remapping, why?

besides, the following errors always occur
![image](https://user-images.githubusercontent.com/24712670/109245065-c684b200-781a-11eb-993e-b249865213ce.png)

those files exists but can't be removed, why

**Comment by SdeBlank** [comment]
I fixed the file removal so the files are correctly removed and no errors should show up anymore. Again updated the 'master' branch

For last remapping, it could be that fusions after LAST remapping are filtered out. Perhaps try to use '-df' to get all fusions even filtered ones.
