### ISSUE TITLE
Does NanoFG work on RNA sequencing?

### ISSUE THREAD

**Issue by nadiadavidson** [SdeBlank/NanoFG#18]
Hi, 
Just a quick question. Is it correct that NanoFG is designed for genomic DNA sequencing and not transcriptome sequencing?

Many thanks for your reply.

Cheers,
Nadia.

**Comment by SdeBlank** [comment]
Hey,

NanoFG was indeed designed and tested for genomic DNA sequencing (Third generation Nanopore sequencing). However, it might also work on long-read transcriptome sequencing if the input is still a 'fastq' or 'bam' file, but I have not tried this myself.

Cheers,
Sam

**Comment by nadiadavidson** [comment]
Thanks for your answer and fast reply!
